### ISSUE TITLE
segmentation fault while deleting LED instances

### ISSUE THREAD

**Issue by maxakuru** [hyperion-project/hyperion.ng#1466]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hitting a seg fault when deleting an LED hardware instance via web UI in 2.0.12 on Raspberry Pi Zero W (Buster).

Initially it seemed to be related to the WLED integration, but not sure now. I tried changing the instance from `wled` to `file > /dev/null`, but the problem stuck around. Clearing db works to remove the instance, but logging this in case others can reproduce.

#### Steps to reproduce
1. Configure default instance (spi)
2. Create instance (philips hue)
3. Create instance (wled)
4. Delete instance (wled or hue)

#### What is expected?
Should remove the instance

#### What is actually happening?
seg fault in `libQt5Core`

#### System
```
Hyperion Server: 
- Build:           (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177)
- Build time:      Nov 21 2021 17:25:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /home/pi/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.83+ (WS: 32))
- Root/Admin:     false
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
```

#### Debug log & backtrace
```sh
(gdb) run -d
Starting program: /usr/bin/hyperiond -d
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
2022-05-15T21:06:12.705  MAIN                  : <INFO> Starting Hyperion - 2.0.12, (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177), built: Nov 21 2021:17:25:08
2022-05-15T21:06:12.711  MAIN                  : <DEBUG> main.cpp:397:main() | QtVersion [5.11.3]
2022-05-15T21:06:12.712  MAIN                  : <INFO> Set user data path to '/home/pi/.hyperion'
[New Thread 0xb27183c0 (LWP 1891)]
2022-05-15T21:06:14.603  DAEMON                : <DEBUG> PythonInit.cpp:75:PythonInit() | Initializing Python interpreter
2022-05-15T21:06:15.068  SETTINGSMGR           : <DEBUG> SettingsManager.cpp:186:SettingsManager() | Settings database initialized
[New Thread 0xb1e173c0 (LWP 1892)]
2022-05-15T21:06:15.076  DAEMON                : <INFO> CEC handler created
2022-05-15T21:06:15.156  EFFECTFILES           : <INFO> 40 effects loaded from directory :/effects/
2022-05-15T21:06:15.190  EFFECTFILES           : <INFO> 22 effect schemas loaded from directory :/effects/schema/
2022-05-15T21:06:15.193  EFFECTFILES           : <INFO> 0 effects loaded from directory /home/pi/.hyperion/custom-effects/
2022-05-15T21:06:15.484  SETTINGSMGR           : <DEBUG> SettingsManager.cpp:186:SettingsManager() | Settings database initialized
2022-05-15T21:06:15.513  BLACKBORDER           : <DEBUG> BlackBorderProcessor.cpp:64:handleSettingsUpdate() | Set mode to: default
2022-05-15T21:06:15.515  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | Blackborder detector: enabled
[New Thread 0xb14ff3c0 (LWP 1893)]
[New Thread 0xb0aff3c0 (LWP 1894)]
2022-05-15T21:06:15.650  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | Smoothing: enabled
2022-05-15T21:06:15.652  LEDDEVICE             : <INFO> Start LedDevice 'sk6812spi'.
2022-05-15T21:06:15.660  LEDDEVICE             : <DEBUG> LedDevice.cpp:148:init() | deviceConfig: [{"colorOrder":"grb","currentLedCount":250,"hardwareLedCount":250,"invert":false,"latchTime":0,"output":"/dev/spidev0.0","rate":3000000,"rewriteTime":1000,"type":"sk6812spi","whiteAlgorithm":"subtract_minimum"}]
2022-05-15T21:06:15.669  LEDDEVICE             : <DEBUG> LedDevice.cpp:414:setLatchTime() | LatchTime updated to 0ms
2022-05-15T21:06:15.655  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | cfg [0]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2022-05-15T21:06:15.677  LEDDEVICE             : <DEBUG> LedDevice.cpp:439:setRewriteTime() | Refresh interval = 1000ms
2022-05-15T21:06:15.680  LEDDEVICE             : <DEBUG> LedDevice.cpp:445:setRewriteTime() | RewriteTime updated to 1000ms
2022-05-15T21:06:15.688  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | Previous line repeats 1 times
2022-05-15T21:06:15.684  LEDDEVICE             : <DEBUG> ProviderSpi.cpp:59:init() | _baudRate_Hz [3000000], _latchTime_ms [0]
2022-05-15T21:06:15.695  LEDDEVICE             : <DEBUG> ProviderSpi.cpp:60:init() | _spiDataInvert [0], _spiMode [0]
2022-05-15T21:06:15.698  LEDDEVICE             : <DEBUG> LedDeviceSk6812SPI.cpp:41:init() | whiteAlgorithm : subtract_minimum
2022-05-15T21:06:15.705  EFFECTENGINE          : <INFO> Run effect "Rainbow swirl fast" on channel 1
2022-05-15T21:06:15.716  EFFECTENGINE          : <DEBUG> EffectEngine.cpp:181:runEffectScript() | Start the effect: name [Rainbow swirl fast], smoothCfg [2]
2022-05-15T21:06:15.720  HYPERION              : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/EFFECT' with priority 1 as inactive
[New Thread 0xb02fe3c0 (LWP 1895)]
2022-05-15T21:06:15.736  HYPERION              : <INFO> Initial foreground effect 'Rainbow swirl fast' started
2022-05-15T21:06:15.764  HYPERION              : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/V4L' with priority 100 as inactive
2022-05-15T21:06:15.766  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | V4L capture device: enabled
2022-05-15T21:06:15.774  BOBLIGHT              : <DEBUG> BoblightServer.cpp:28:BoblightServer() | Instance created
2022-05-15T21:06:15.778  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | LED device: enabled
2022-05-15T21:06:15.955  SETTINGSMGR           : <DEBUG> SettingsManager.cpp:186:SettingsManager() | Settings database initialized
2022-05-15T21:06:15.984  BLACKBORDER           : <DEBUG> BlackBorderProcessor.cpp:64:handleSettingsUpdate() | Set mode to: default
2022-05-15T21:06:15.986  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | Blackborder detector: enabled
[New Thread 0xafafd3c0 (LWP 1896)]
[New Thread 0xaf2fc3c0 (LWP 1897)]
2022-05-15T21:06:16.094  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | Smoothing: enabled
2022-05-15T21:06:16.096  LEDDEVICE             : <INFO> Start LedDevice 'file'.
2022-05-15T21:06:16.110  LEDDEVICE             : <DEBUG> LedDevice.cpp:148:init() | deviceConfig: [{"colorOrder":"rgb","currentLedCount":1,"hardwareLedCount":1,"latchTime":0,"output":"/dev/null","printTimeStamp":false,"rewriteTime":1000,"type":"file"}]
2022-05-15T21:06:16.115  LEDDEVICE             : <DEBUG> LedDevice.cpp:414:setLatchTime() | LatchTime updated to 0ms
2022-05-15T21:06:16.119  LEDDEVICE             : <DEBUG> LedDevice.cpp:439:setRewriteTime() | Refresh interval = 1000ms
2022-05-15T21:06:16.122  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | cfg [0]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2022-05-15T21:06:16.129  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | Previous line repeats 1 times
2022-05-15T21:06:16.143  LEDDEVICE             : <DEBUG> LedDevice.cpp:445:setRewriteTime() | RewriteTime updated to 1000ms
2022-05-15T21:06:16.146  LEDDEVICE             : <DEBUG> LedDeviceFile.cpp:59:open() | QIODevice::WriteOnly, /dev/null
2022-05-15T21:06:16.149  EFFECTENGINE          : <INFO> Run effect "Rainbow swirl fast" on channel 1
2022-05-15T21:06:16.160  EFFECTENGINE          : <DEBUG> EffectEngine.cpp:181:runEffectScript() | Start the effect: name [Rainbow swirl fast], smoothCfg [2]
2022-05-15T21:06:16.163  HYPERION              : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/EFFECT' with priority 1 as inactive
[New Thread 0xaeafb3c0 (LWP 1898)]
2022-05-15T21:06:16.187  HYPERION              : <INFO> Initial foreground effect 'Rainbow swirl fast' started
2022-05-15T21:06:16.205  BOBLIGHT              : <DEBUG> BoblightServer.cpp:28:BoblightServer() | Instance created
2022-05-15T21:06:16.214  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | LED device: enabled
2022-05-15T21:06:16.474  SETTINGSMGR           : <DEBUG> SettingsManager.cpp:186:SettingsManager() | Settings database initialized
2022-05-15T21:06:16.490  BLACKBORDER           : <DEBUG> BlackBorderProcessor.cpp:64:handleSettingsUpdate() | Set mode to: default
2022-05-15T21:06:16.492  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | Blackborder detector: enabled
[New Thread 0xae2fa3c0 (LWP 1899)]
2022-05-15T21:06:16.587  DAEMON                : <INFO> set screen capture device to 'dispmanx'
[New Thread 0xadab93c0 (LWP 1900)]
[New Thread 0xad2b83c0 (LWP 1901)]
[New Thread 0xacab73c0 (LWP 1902)]
2022-05-15T21:06:16.623  LEDDEVICE             : <INFO> Start LedDevice 'file'.
2022-05-15T21:06:16.638  LEDDEVICE             : <DEBUG> LedDevice.cpp:148:init() | deviceConfig: [{"colorOrder":"rgb","currentLedCount":1,"hardwareLedCount":1,"latchTime":0,"output":"/dev/null","printTimeStamp":false,"rewriteTime":1000,"type":"file"}]
[New Thread 0xac2b63c0 (LWP 1903)]
2022-05-15T21:06:16.649  LEDDEVICE             : <DEBUG> LedDevice.cpp:414:setLatchTime() | LatchTime updated to 0ms
2022-05-15T21:06:16.640  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | cfg [0]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2022-05-15T21:06:16.660  LEDDEVICE             : <DEBUG> LedDevice.cpp:439:setRewriteTime() | Refresh interval = 1000ms
[New Thread 0xabab53c0 (LWP 1904)]
2022-05-15T21:06:16.678  DAEMON                : <INFO> DISPMANX frame grabber created
2022-05-15T21:06:16.674  LEDDEVICE             : <DEBUG> LedDevice.cpp:445:setRewriteTime() | RewriteTime updated to 1000ms
2022-05-15T21:06:16.689  LEDDEVICE             : <DEBUG> LedDeviceFile.cpp:59:open() | QIODevice::WriteOnly, /dev/null
2022-05-15T21:06:16.670  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | Previous line repeats 1 times
2022-05-15T21:06:16.695  EFFECTENGINE          : <INFO> Run effect "Rainbow swirl fast" on channel 1
2022-05-15T21:06:16.706  EFFECTENGINE          : <DEBUG> EffectEngine.cpp:181:runEffectScript() | Start the effect: name [Rainbow swirl fast], smoothCfg [2]
2022-05-15T21:06:16.713  HYPERION              : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/EFFECT' with priority 1 as inactive
2022-05-15T21:06:16.703  V4L2                  : <DEBUG> Grabber.cpp:141:setWidthHeight() | Set new width: 800, height: 600 for capture
2022-05-15T21:06:16.725  V4L2                  : <INFO> Set new frames per second to: 20 fps
2022-05-15T21:06:16.729  V4L2                  : <INFO> Set flipmode to NO_CHANGE
[New Thread 0xab2b43c0 (LWP 1905)]
2022-05-15T21:06:16.741  HYPERION              : <INFO> Initial foreground effect 'Rainbow swirl fast' started
[New Thread 0xaaab33c0 (LWP 1906)]
2022-05-15T21:06:16.774  BOBLIGHT              : <DEBUG> BoblightServer.cpp:28:BoblightServer() | Instance created
2022-05-15T21:06:16.783  COMPONENTREG          : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | LED device: enabled
2022-05-15T21:06:17.148  V4L2                  : <DEBUG> V4L2Grabber.cpp:151:init() | Set device (path) to: UVC Camera (534d:2109): USB Vid (/dev/video0)
2022-05-15T21:06:17.154  V4L2                  : <DEBUG> V4L2Grabber.cpp:488:init_device() | Set device input to: Camera 1
2022-05-15T21:06:17.161  V4L2                  : <DEBUG> V4L2Grabber.cpp:614:init_device() | Set resolution to width=800 height=600
2022-05-15T21:06:17.167  V4L2                  : <DEBUG> V4L2Grabber.cpp:631:init_device() | Set framerate to 20 fps
2022-05-15T21:06:17.170  V4L2                  : <DEBUG> V4L2Grabber.cpp:707:init_device() | Pixel format=YUYV
2022-05-15T21:06:17.196  V4L2                  : <INFO> Started
2022-05-15T21:06:17.203  DAEMON                : <DEBUG> hyperiond.cpp:608:handleSettingsUpdate() | V4L2 grabber created
2022-05-15T21:06:17.208  JSONSERVER            : <DEBUG> JsonServer.cpp:28:JsonServer() | Created instance
2022-05-15T21:06:17.227  JSONSERVER            : <INFO> Started on port 19444
[New Thread 0xa9c6d3c0 (LWP 1907)]
[New Thread 0xa946c3c0 (LWP 1908)]
[New Thread 0xa8c6b3c0 (LWP 1909)]
2022-05-15T21:06:19.040  PROTOSERVER           : <INFO> Started on port 19445
2022-05-15T21:06:19.030  FLATBUFSERVER         : <INFO> Started on port 19400
[New Thread 0xa846a3c0 (LWP 1910)]
[New Thread 0xa7c693c0 (LWP 1911)]
2022-05-15T21:06:19.085  WEBSERVER             : <DEBUG> WebServer.cpp:33:initServer() | Initialize Webserver
[New Thread 0xa74683c0 (LWP 1912)]
2022-05-15T21:06:19.117  WEBSERVER             : <DEBUG> WebServer.cpp:33:initServer() | Initialize Webserver
[New Thread 0xa6c673c0 (LWP 1913)]
2022-05-15T21:06:19.193  HYPERION              : <INFO> Hyperion instance 'ambilight' has been started
2022-05-15T21:06:19.204  HYPERION              : <INFO> Hyperion instance 'diyhue' has been started
2022-05-15T21:06:19.214  HYPERION              : <INFO> Hyperion instance 'console' has been started
2022-05-15T21:06:19.244  HYPERION              : <DEBUG> PriorityMuxer.cpp:271:setInputImage() | Priority 100 is now active
2022-05-15T21:06:19.247  HYPERION              : <DEBUG> PriorityMuxer.cpp:374:setCurrentTime() | Set visible priority to 100
2022-05-15T21:06:19.260  HYPERION              : <DEBUG> Hyperion.cpp:571:handleSourceAvailability() | priority[100], previousPriority[255]
2022-05-15T21:06:19.272  HYPERION              : <DEBUG> Hyperion.cpp:582:handleSourceAvailability() | new source available -> Resume output processing and switch LED-Device on
2022-05-15T21:06:20.491  WEBSERVER             : <DEBUG> WebServer.cpp:92:handleSettingsUpdate() | Apply Webserver settings
2022-05-15T21:06:20.495  WEBSERVER             : <DEBUG> WebServer.cpp:110:handleSettingsUpdate() | Set document root to: :/webconfig
2022-05-15T21:06:20.510  WEBSERVER             : <DEBUG> WebServer.cpp:92:handleSettingsUpdate() | Apply Webserver settings
2022-05-15T21:06:20.534  WEBSERVER             : <DEBUG> WebServer.cpp:110:handleSettingsUpdate() | Set document root to: :/webconfig
2022-05-15T21:06:20.550  WEBSERVER             : <INFO> 'Hyperion Webserver' started on port 8090
2022-05-15T21:06:20.685  WEBSERVER             : <DEBUG> WebServer.cpp:176:handleSettingsUpdate() | Setup SSL certificate
2022-05-15T21:06:20.699  WEBSERVER             : <DEBUG> WebServer.cpp:192:handleSettingsUpdate() | Setup private SSL key
2022-05-15T21:06:20.719  WEBSERVER             : <INFO> 'Hyperion Webserver' started on port 8092
[New Thread 0xa5b3a3c0 (LWP 1915)]
[New Thread 0xa633b3c0 (LWP 1914)]
2022-05-15T21:06:21.495  EFFECTENGINE          : <INFO> effect finished
[Thread 0xb02fe3c0 (LWP 1895) exited]
[New Thread 0xb02fe3c0 (LWP 1916)]
[New Thread 0xa53393c0 (LWP 1917)]
[New Thread 0xa4a1f3c0 (LWP 1918)]
2022-05-15T21:06:23.747  HYPERION              : <DEBUG> PriorityMuxer.cpp:271:setInputImage() | Priority 1 is now active
2022-05-15T21:06:23.765  HYPERION              : <DEBUG> PriorityMuxer.cpp:374:setCurrentTime() | Set visible priority to 1
2022-05-15T21:06:23.778  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | cfg [2]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2022-05-15T21:06:23.798  HYPERION              : <DEBUG> Hyperion.cpp:571:handleSourceAvailability() | priority[1], previousPriority[255]
2022-05-15T21:06:23.813  HYPERION              : <DEBUG> Hyperion.cpp:582:handleSourceAvailability() | new source available -> Resume output processing and switch LED-Device on
2022-05-15T21:06:24.473  HYPERION              : <DEBUG> PriorityMuxer.cpp:271:setInputImage() | Priority 1 is now active
2022-05-15T21:06:24.479  HYPERION              : <DEBUG> PriorityMuxer.cpp:374:setCurrentTime() | Set visible priority to 1
2022-05-15T21:06:24.488  HYPERION              : <DEBUG> Hyperion.cpp:571:handleSourceAvailability() | priority[1], previousPriority[255]
2022-05-15T21:06:24.500  HYPERION              : <DEBUG> Hyperion.cpp:582:handleSourceAvailability() | new source available -> Resume output processing and switch LED-Device on
[New Thread 0xa41fd3c0 (LWP 1919)]
2022-05-15T21:06:25.583  HYPERION              : <DEBUG> PriorityMuxer.cpp:337:setCurrentTime() | Timeout clear for priority 1
2022-05-15T21:06:25.589  HYPERION              : <DEBUG> PriorityMuxer.cpp:374:setCurrentTime() | Set visible priority to 255
2022-05-15T21:06:25.593  SMOOTHING             : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | cfg [0]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2022-05-15T21:06:25.603  HYPERION              : <DEBUG> Hyperion.cpp:571:handleSourceAvailability() | priority[255], previousPriority[1]
2022-05-15T21:06:25.611  HYPERION              : <DEBUG> Hyperion.cpp:574:handleSourceAvailability() | No source left -> Pause output processing and switch LED-Device off
2022-05-15T21:06:26.025  EFFECTENGINE          : <INFO> effect finished
[Thread 0xa53393c0 (LWP 1917) exited]
[Thread 0xaeafb3c0 (LWP 1898) exited]
[New Thread 0xaeafb3c0 (LWP 1920)]
2022-05-15T21:06:26.584  HYPERION              : <DEBUG> PriorityMuxer.cpp:337:setCurrentTime() | Timeout clear for priority 1
2022-05-15T21:06:26.590  HYPERION              : <DEBUG> PriorityMuxer.cpp:374:setCurrentTime() | Set visible priority to 255
2022-05-15T21:06:26.596  HYPERION              : <DEBUG> Hyperion.cpp:571:handleSourceAvailability() | priority[255], previousPriority[1]
2022-05-15T21:06:26.614  HYPERION              : <DEBUG> Hyperion.cpp:574:handleSourceAvailability() | No source left -> Pause output processing and switch LED-Device off
[Thread 0xaeafb3c0 (LWP 1920) exited]
2022-05-15T21:06:26.892  EFFECTENGINE          : <INFO> effect finished
[Thread 0xab2b43c0 (LWP 1905) exited]
2022-05-15T21:06:38.656  WEBSOCKET             : <DEBUG> WebSocketClient.cpp:30:WebSocketClient() | New connection from ::ffff:192.168.1.171
2022-05-15T21:06:39.028  JSONSERVER            : <DEBUG> JsonServer.cpp:105:newConnection() | New connection from: ::ffff:192.168.1.99
2022-05-15T21:06:39.558  WEBSOCKET             : <DEBUG> JsonAPI.cpp:122:handleInstanceSwitch() | Client '::ffff:192.168.1.171' switch to Hyperion instance 1
2022-05-15T21:06:47.709  HYPERION              : <INFO> Hyperion instance 'console' has been stopped
2022-05-15T21:06:47.714  LEDDEVICE             : <DEBUG> LedDeviceFile.cpp:85:close() | File: /dev/null
2022-05-15T21:06:47.721  LEDDEVICE             : <INFO>  Stopped LedDevice 'file'
[Thread 0xad2b83c0 (LWP 1901) exited]

Thread 1 "hyperiond" received signal SIGSEGV, Segmentation fault.
0xb5afece4 in QObject::thread() const () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
(gdb) bt
#0  0xb5afece4 in QObject::thread() const () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#1  0x000b8f8c in Hyperion::stop() ()
#2  0x000c31d0 in HyperionIManager::stopInstance(unsigned char) ()
#3  0x000c3388 in HyperionIManager::deleteInstance(unsigned char) ()
#4  0x000e75f4 in HyperionIManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#5  0xb5b01bec in QObject::event(QEvent*) () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#6  0xb5ad42c0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#7  0xb5ad77bc in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#8  0xb5b3030c in ?? () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#9  0xb4c40c5c in g_main_context_dispatch () from /lib/arm-linux-gnueabihf/libglib-2.0.so.0
#10 0xb4c40e7c in ?? () from /lib/arm-linux-gnueabihf/libglib-2.0.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by Lord-Grey** [comment]
@maxakuru Thanks for sharing the finding.
Does the problem still exist with Hyperion 2.0.13?
Thx.

**Comment by maxakuru** [comment]
@Lord-Grey sorry for the late reply. 

Just upgraded and it *seemed* to have the same issue with deleting a Hue instance, but a WLED instance could be deleted fine. I ignored SIGPIPEs in gdb and tried again and it worked fine to delete; I'm not able to reproduce so I'd call it closed 🤷‍♂️ 

In case others hit this and need the same process for a workaround:
```sh
gdb
exec-file hyperiond
handle SIGPIPE nostop noprint pass
run -d
```
