### ISSUE TITLE
Hyperion cores selectively during quit

### ISSUE THREAD

**Issue by Lord-Grey** [hyperion-project/hyperion.ng#668]
Hyperion.NG sometimes ends with a Segmentation fault and cores.

```
[hyperiond HYPERION] <INFO> Hyperion instance 'First LED Hardware instance' has been started
^C
[hyperiond MAIN] <INFO> Application closed with code 0
[hyperiond FLATBUFSERVER] <INFO> Stopped
Segmentation fault (core dumped)
```
The related code is during quiting the various Qt Treads.

```

...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./build-x86x64/bin/hyperiond'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f53027f4e98 in QObject::thread() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
[Current thread is 1 (Thread 0x7f52ff808800 (LWP 25146))]
(gdb) bt
#0  0x00007f53027f4e98 in QObject::thread() const () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x0000562e7e8db408 in HyperionDaemon::freeObjects() (this=0x562e7ff31100) at /home/thomas/hyperion.ng/src/hyperiond/hyperiond.cpp:166
#2  0x0000562e7e8db261 in HyperionDaemon::~HyperionDaemon() (this=0x562e7ff31100, __in_chrg=<optimised out>) at /home/thomas/hyperion.ng/src/hyperiond/hyperiond.cpp:142
#3  0x0000562e7e8db2f2 in HyperionDaemon::~HyperionDaemon() (this=0x562e7ff31100, __in_chrg=<optimised out>) at /home/thomas/hyperion.ng/src/hyperiond/hyperiond.cpp:145
#4  0x0000562e7e8ebf52 in main(int, char**) (argc=1, argv=0x7ffe00f498a8) at /home/thomas/hyperion.ng/src/hyperiond/main.cpp:379
```

```
void HyperionDaemon::freeObjects()
{
	// destroy network first as a client might want to access hyperion
	delete _jsonServer;
	_flatBufferServer->thread()->quit();
	_flatBufferServer->thread()->wait(1000);
	_protoServer->thread()->quit();
->	_protoServer->thread()->wait(1000);
	//ssdp before webserver
	_ssdp->thread()->quit();
	_ssdp->thread()->wait(1000);
	_webserver->thread()->quit();
	_webserver->thread()->wait(1000);
	_sslWebserver->thread()->quit();
	_sslWebserver->thread()->wait(1000);
```

**Comment by Lord-Grey** [comment]
Looking at the implementation of the different network related classes, it seems that the Qt Tread affinity is not considered properly (similar as in LedDeviceWrapper & LedDevice).
I will have a look after the PR654 has been merged with the master branch to ring-fence any updates.

**Comment by tpmodding** [comment]
Stand der Dinge? lassen?

**Comment by Lord-Grey** [comment]
@tpmodding Issue is still open and requires further investigation.
