### ISSUE TITLE
ZipImportError: can't decompress data; zlib not available

### ISSUE THREAD

**Issue by RaymondMouthaan** [hyperion-project/hyperion.ng#881]
- [x] I confirm that this is an issue rather than a question.

## Bug report

After compiling a new hyperion using the following docker command:

```
wget -qN https://raw.github.com/hyperion-project/hyperion.ng/master/bin/scripts/docker-compile.sh && chmod +x *.sh && ./docker-compile.sh -t armv7hf
```

And copying the .deb to my Raspberry PI, I installed the .deb using following command:

```
sudo apt install ./Hyperion-2.0.0-alpha.6-Linux-armv7l.deb
```

After installing the following errors occurred. Especially the Python exception is worrying, since it makes Hyperion crash and makes it restart in a loop. 

```
Jul 17 15:09:32 hyperion-2 hyperiond[813]: [hyperiond DISPMANXGRABBER] <ERROR> Failed to open display! Probably no permissions to access the capture interface
Jul 17 15:09:32 hyperion-2 hyperiond[813]: Failed to open display! Probably no permissions to access the capture interface
Jul 17 15:09:34 hyperion-2 hyperiond[813]: [hyperiond EFFECTENGINE] <ERROR> ###### PYTHON EXCEPTION ######
Jul 17 15:09:34 hyperion-2 hyperiond[813]: [hyperiond EFFECTENGINE] <ERROR> ## In effect 'Rainbow swirl fast'
Jul 17 15:09:34 hyperion-2 hyperiond[813]: [hyperiond EFFECTENGINE] <ERROR> ## ZipImportError: can't decompress data; zlib not available
Jul 17 15:09:34 hyperion-2 hyperiond[813]: ###### PYTHON EXCEPTION ######
Jul 17 15:09:34 hyperion-2 hyperiond[813]: ## In effect 'Rainbow swirl fast'
Jul 17 15:09:34 hyperion-2 hyperiond[813]: ## ZipImportError: can't decompress data; zlib not available
```

Checks:

Following command returns nothing:

```
python3 -c "import zlib"
```

```
sudo apt install zlib1g-dev
```
returns `zlib1g-dev is already the newest version (1:1.2.11.dfsg-1).`

Also installing the following packages on the hyperion pi did not make any difference :

```
sudo apt-get install git cmake build-essential qtbase5-dev libqt5serialport5-dev libusb-1.0-0-dev python3-dev libxcb-util0-dev libxcb-randr0-dev libxrandr-dev libxrender-dev libavahi-core-dev libavahi-compat-libdnssd-dev libjpeg-dev libturbojpeg0-dev libqt5sql5-sqlite libssl-dev zlib1g-dev
```

**Update:** when compiling and installing on the RPI directly, above zlib error doesn't occur.

#### Steps to reproduce
See above

#### What is expected?
Hyperion starting successfully. 

#### What is actually happening?
Hyperion crashes and restarts in a loop

**Comment by RaymondMouthaan** [comment]
same error happens when downloading and installing:

```
wget https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.7/Hyperion-2.0.0-alpha.7-Linux-armv6l.tar.gz

sudo apt install ./Hyperion-2.0.0-alpha.7-Linux-armv6l.deb
```


when running `hyperiond`, I get this error:

```
2020-07-24T22:15:31.496 hyperiond DISPMANXGRAB : <ERROR> Failed to open display! Probably no permissions to access the capture interface
2020-07-24T22:15:32.372 hyperiond EFFECTENGINE : <ERROR> ###### PYTHON EXCEPTION ######
2020-07-24T22:15:32.372 hyperiond EFFECTENGINE : <ERROR> ## In effect 'Rainbow swirl fast'
2020-07-24T22:15:32.373 hyperiond EFFECTENGINE : <ERROR> ## ZipImportError: can't decompress data; zlib not available
2020-07-24T22:15:33.205 hyperiond EFFECTENGINE : <ERROR> ## Traceback (most recent call last):
2020-07-24T22:15:33.205 hyperiond EFFECTENGINE : <ERROR> ## File "<string>", line 1, in <module>
2020-07-24T22:15:33.206 hyperiond EFFECTENGINE : <ERROR> ## File "/usr/share/hyperion/bin/python35.zip/random.py", line 40, in <module>
    from types import MethodType as _MethodType, BuiltinMethodType as _BuiltinMethodType
2020-07-24T22:15:33.206 hyperiond EFFECTENGINE : <ERROR> ## File "/usr/share/hyperion/bin/python35.zip/types.py", line 166, in <module>
    import functools as _functools
2020-07-24T22:15:33.206 hyperiond EFFECTENGINE : <ERROR> ## File "/usr/share/hyperion/bin/python35.zip/functools.py", line 21, in <module>
    from collections import namedtuple
2020-07-24T22:15:33.206 hyperiond EFFECTENGINE : <ERROR> ## File "/usr/share/hyperion/bin/python35.zip/collections/__init__.py", line 32, in <module>
    from reprlib import recursive_repr as _recursive_repr
2020-07-24T22:15:33.206 hyperiond EFFECTENGINE : <ERROR> ## zipimport.ZipImportError: can't decompress data; zlib not available
2020-07-24T22:15:33.206 hyperiond EFFECTENGINE : <ERROR> ###### EXCEPTION END ######

Hyperion caught signal :SIGSEGV
2020-07-24T22:15:34.002 hyperiond CORE         : <ERROR> 	/lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0x7569a130]
2020-07-24T22:15:34.003 hyperiond CORE         : <ERROR> 	/usr/share/hyperion/bin/../lib/libQt5Core.so.5(QRingBuffer::reserve(long long)+0x44) [0x75b6fb74]
Segmentation fault
raymond@hyperion-1:~ $ hyperiond
2020-07-24T22:17:40.375 hyperiond DISPMANXGRAB : <ERROR> Failed to open display! Probably no permissions to access the capture interface
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/share/hyperion/bin/python35.zip/io.py", line 52, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available

Hyperion caught signal :SIGABRT
2020-07-24T22:17:40.679 hyperiond CORE         : <ERROR> 	/lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0x755ae130]
Aborted
```

Someone knows what I am doing wrong/missing here?

**Comment by RaymondMouthaan** [comment]
You can try the following temporary fix.
Unzip the python35.zip file in the "hyperion/bin" directory to "hyperion/lib/python". then delete the zip file and restart.

`sudo systemctl stop hyperiond@pi.service`
`sudo mkdir /usr/share/hyperion/lib/python/`
`sudo unzip /usr/share/hyperion/bin/python35.zip -d /usr/share/hyperion/lib/python`
`sudo rm /usr/share/hyperion/bin/python35.zip`
`sudo reboot`

_Originally posted by @Paulchen-Panther in https://github.com/hyperion-project/hyperion.ng/issues/903#issuecomment-663840462_

**Comment by jschwalbe** [comment]
This worked for me -- the above comments about installing and verifying zlib already installed applies. (However, I'm using debian and I just grabbed it from https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.7/Hyperion-2.0.0-alpha.7-Linux-x86_64.tar.gz)

**Comment by fightforlife** [comment]
Same issue here on Ubuntu 20,04. Package is already installed but not found by hyperion.

**Comment by tpmodding** [comment]
@Paulchen-Panther status? can this be closed?

**Comment by Paulchen-Panther** [comment]
Yes
